### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by stasadance** [TyounanMOTI/UnityASUSAura#1]
Did you ever get this to work past alpha? I tried myself but it doesn't set any LEDs, would be cool to create a .NET or JS sdk with this, I'm no C++ guy so would be amazing if we can get it to work 👍

**Comment by TyounanMOTI** [comment]
Nothing is done after first alpha, but I will continue work for this code.
Currently, I'm waiting for answer from ASUS regarding Apply() function takes 1 second. It's too much to implement custom effects like spectrum analyzer.

I have no plan to develop a .NET or JS sdk because I don't yet understand how to make it.

> I tried myself but it doesn't set any LEDs,
Would you rebuild the plugin with ASUS Aura SDK? Somehow it made work in my colleague's environment.

**Comment by stasadance** [comment]
Ok cool I hope to see this become something bigger when they fix all their bugs :)
